<script setup>
import {ref,onMounted,onUnmounted} from 'vue';
import {version as appVersion} from '../package.json';
import {invoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import SetupGuide from './SetupGuide.vue';
import {HardDrive,RefreshCw,ArrowUpRight,ShieldCheck,Settings,Download,FolderOpen,LogOut,CheckCircle2} from 'lucide-vue-next';
const state=ref(null),page=ref('disks'),busy=ref(false),notice=ref(''),error=ref(false),backend=ref('Auto'),update=ref(null),updateText=ref(''),updating=ref(false),progress=ref(0);
const autoMount=ref(true);
let timer,unlistenDevices,unlistenResult,unlistenUpdate;
async function refresh(){try{state.value=await invoke('snapshot');backend.value=state.value.settings.backend;autoMount.value=state.value.settings.auto_mount;}catch(e){show(e,true)}}
function show(message,isError=false){notice.value=String(message);error.value=isError}
async function act(action,volume=null){if(busy.value)return;busy.value=true;notice.value='';try{show(await invoke('operate',{action,volume,backend:backend.value}));}catch(e){show(e,true)}finally{busy.value=false;await refresh()}}
async function save(){try{await invoke('save_settings',{settings:{backend:backend.value,dark:false,auto_mount:autoMount.value}})}catch(e){show(e,true)}}
async function updates(quiet=false){try{update.value=await invoke('check_updates');updateText.value=update.value?`发现新版本 ${update.value.version}`:'已是最新版本';}catch(e){updateText.value=quiet?'暂时无法检查更新，离线功能可继续使用':`检查更新失败：${String(e)}`}}
async function installUpdate(){if(!update.value||busy.value||updating.value)return;updating.value=true;progress.value=0;try{await invoke('install_update')}catch(e){show(`更新失败：${String(e)}。请重新检查更新后重试。`,true)}finally{updating.value=false}}
function size(n){return n?(n/1e9).toFixed(1)+' GB':'—'}
onMounted(async()=>{await refresh();unlistenDevices=await listen('devices-changed',()=>refresh());unlistenResult=await listen('operation-result',event=>{show(event.payload.message,event.payload.error);refresh()});unlistenUpdate=await listen('update-progress',event=>{const {received,total}=event.payload;progress.value=total?Math.round(received/total*100):0});updates(true);timer=setInterval(()=>{if(!busy.value)refresh()},8000)});onUnmounted(()=>{clearInterval(timer);unlistenDevices?.();unlistenResult?.();unlistenUpdate?.()});
</script>
<template>
<div class="shell">
<aside><div class="brand"><span class="logo"><HardDrive :size="23"/></span><div>macntfs<small>磁盘，自由读写。</small></div></div><div class="nav-label">工作空间</div><button :class="{active:page==='disks'}" @click="page='disks'"><HardDrive :size="18"/> 我的磁盘</button><button :class="{active:page==='settings'}" @click="page='settings'"><Settings :size="18"/> 设置与更新</button><div class="aside-footer"><span class="dot"></span> 本地运行 · 离线可用<small>免费开源 / v{{state?.version||appVersion}}</small></div></aside>
<main><header><div><span class="eyebrow">NTFS FOR MAC</span><h1>{{page==='disks'?'我的磁盘':'设置与更新'}}</h1><p>{{page==='disks'?'连接外置 NTFS 磁盘，轻松管理读写。':'管理读写组件和 GitHub 版本更新。'}}</p></div><div class="header-actions"><button class="secondary" @click="page='settings'">首次使用向导</button><button class="secondary" @click="refresh" :disabled="busy"><RefreshCw :size="16"/> 刷新</button></div></header>
<section v-if="state && (!state.environment.runtime||!state.environment.fuse)" class="setup"><div class="icon"><ShieldCheck/></div><div><h3>完成读写组件安装</h3><p>{{!state.environment.runtime?'安装或更新内置读写组件，即可继续使用。':'请安装内置 macFUSE，并完成 macOS 系统授权。'}}</p><small>安装资源随软件提供，无需联网。</small></div><button class="primary" :disabled="busy" @click="act('install')">安装组件 <ArrowUpRight :size="16"/></button></section>
<section v-if="state && state.environment.runtime && state.environment.fuse && !state.environment.service" class="setup"><div class="icon"><ShieldCheck/></div><div><h3>后台助手连接异常</h3><p>{{state?.environment.service_issue}}</p><small>已安装完整 PKG 时，请先退出旧版本和测试实例，再从「应用程序」启动。</small></div><button class="primary" :disabled="busy" @click="act('release')">完整安装包 <Download :size="16"/></button></section>
<section v-if="notice" class="notice" :class="{error}"><strong>{{notice.split('\n')[0]}}</strong><button v-if="error && notice.includes('macOS 拒绝访问磁盘设备')" class="permission-button secondary" :disabled="busy" @click="act('permissions')">打开磁盘访问权限设置 <ArrowUpRight :size="15"/></button><button v-if="error && notice.includes('macOS 拒绝访问磁盘设备')" class="permission-button secondary" :disabled="busy" @click="act('permission-helper')">打开助手位置 <FolderOpen :size="15"/></button><details v-if="notice.includes('\n')"><summary>技术详情</summary><pre>{{notice.split('\n').slice(1).join('\n')}}</pre></details><button class="dismiss" @click="notice=''">×</button></section>
<template v-if="page==='disks'"><div class="section-title"><h2>外置磁盘 <span>{{state?.volumes.length||0}}</span></h2><span>{{state?.monitor.busy?'正在自动开启读写…':'实时设备检测'}}</span></div><div class="disks"><article v-for="v in state?.volumes" :key="v.uuid" class="disk"><div class="disk-heading"><div class="drive-icon"><HardDrive :size="29"/></div><span class="badge" :class="{writable:v.writable&&v.mount}">{{v.mount?(v.writable?'可读写':'只读'):'未挂载'}}</span></div><h3>{{v.name||'未命名磁盘'}}</h3><p class="device">NTFS · {{v.id}}</p><div class="capacity"><strong>{{size(v.size)}}</strong><span>总容量</span></div><div class="disk-meta"><span>挂载位置</span><span :title="v.mount">{{v.mount||'尚未挂载'}}</span></div><div class="actions"><button class="primary" :disabled="busy||updating" v-if="!v.writable||!v.mount" @click="act('mount',v)">{{busy?'处理中…':'开启读写'}}<ArrowUpRight :size="16"/></button><button class="primary" v-else :disabled="busy" @click="act('open',v)"><FolderOpen :size="16"/> 打开 Finder</button><button class="eject secondary" :disabled="busy" @click="act('eject',v)" title="安全推出整块磁盘，包括其他分区"><LogOut :size="17"/> 推出</button></div></article></div><section v-if="state&&!state.volumes.length" class="empty"><HardDrive :size="48"/><h3>等待连接磁盘</h3><p>连接 NTFS 格式的 USB 磁盘后，会自动显示在这里。</p></section><div class="tip"><ShieldCheck :size="17"/><span>磁盘休眠或文件系统异常时会停止开启读写，保护已有数据。</span></div></template>
<template v-else><SetupGuide :environment="state?.environment" :busy="busy" @action="act" @refresh="refresh"/><section class="setting-card"><h2>菜单栏与自动读写</h2><p>关闭窗口后仍在菜单栏运行。设备插入时自动检查并开启 NTFS 读写；退出应用会停止设备检测。</p><label>插入后自动开启读写<input type="checkbox" v-model="autoMount" @change="save" /></label><div class="setting-row"><span>{{state?.environment.service?'后台助手已就绪 · 日常挂载无需密码':'后台助手连接异常'}}</span></div><p v-if="!state?.environment.service">{{state?.environment.service_issue}}</p><p>安装时如系统提供 Touch ID，可以使用指纹；软件不会保存管理员密码，也不更改系统的验证策略。</p><p v-if="state?.monitor.last_event">最近操作：{{state.monitor.last_event.split('\n')[0]}}</p></section><section class="setting-card"><h2>读写引擎</h2><p>稳定模式使用 macFUSE 内核后端。首次安装可能需要系统授权和重启。</p><label>挂载模式<select v-model="backend" @change="save"><option value="Auto">稳定模式（推荐）</option><option value="Kernel">内核兼容模式</option><option value="Fskit">FSKit（实验性，macOS 15.4+）</option></select></label><div class="setting-row"><span>macFUSE {{state?.environment.fuse_version||'尚未安装'}}</span><button class="secondary" :disabled="busy" @click="act('permissions')">磁盘访问权限</button><button class="secondary" :disabled="busy" @click="act('settings')">系统授权 <ArrowUpRight :size="15"/></button></div></section><section class="setting-card"><h2>磁盘访问授权</h2><p>macOS 管理员密码与隐私授权分别管理。访问磁盘设备需要为权限助手 ntfs-helper 授予完整磁盘访问。此权限范围较广，请只添加本安装包提供的助手；软件仍只对你选择的外置 NTFS 磁盘执行操作。</p><p>当前测试版使用临时签名，更新组件后可能需要在系统设置移除旧助手条目，再添加当前助手。授权后重新启动应用。</p><div class="actions"><button class="secondary" :disabled="busy" @click="act('permissions')">打开完整磁盘访问</button><button class="secondary" :disabled="busy" @click="act('permission-helper')"><FolderOpen :size="16"/>打开助手位置</button></div></section><section class="setting-card"><h2>软件更新 <span class="version">v{{state?.version}}</span></h2><p>启动时自动检查 GitHub Release。完整 PKG 验证签名和版本后打开系统安装器，同时更新应用与助手；离线时读写功能可正常使用。</p><p>当前应用 v{{state?.version}} · 已安装助手 {{state?.environment.runtime_version?`v${state.environment.runtime_version}`:'未安装'}} · {{state?.environment.service?'已连接':'未连接'}}</p><p class="update-text">{{updateText||'正在检查更新…'}}</p><p v-if="update">点下方按钮下载并验证完整安装包。安装器打开后 macntfs 会退出；按系统提示完成安装，再从「应用程序」启动。首次驱动授权和完整磁盘访问不会被自动绕过。</p><div class="actions"><button class="secondary" :disabled="updating" @click="updates()"><RefreshCw :size="16"/> 检查更新</button><button v-if="update" class="primary" :disabled="updating||busy" @click="installUpdate"><Download :size="16"/> {{updating?`正在更新 ${progress}%`:'下载并打开安装器'}}</button></div></section></template>
<footer><CheckCircle2 :size="14"/> {{busy?'操作处理中，请等待系统响应':'所有磁盘操作均在本机完成'}}<span>macOS {{state?.environment.os||'—'}}</span></footer></main></div>
</template>
